name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download_essentials
      run: sudo apt install build-essential
    - name: mkdir
      run: mkdir ~/opt
    - name: download
      run: wget https://drive.google.com/file/d/1xbhr6TyIu4pNZqlmcDxyLudGc7rssXWt/view?usp=sharing -O cross.tar.gz && tar -czrf cross.tar.gz
    - name: prep
      run: export PREFIX="$HOME/opt/cross" && export TARGET=i686-elf && export PATH="$PREFIX/bin:$PATH"
    - name: clone
      run: git clone https://github.com/Jviguy/SexOS ~/
      working-directory: ~/
    - name: iso_build
      run: ./iso.sh
    - uses: actions/upload-artifact@v2
      with:
        name: SexOS
        path: ~/SexOS.iso 
